// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
 ///await Firebase.initializeApp(
   ///options: DefaultFirebaseOptions.currentPlatform,
 ///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDImEGX1M7dJQAkxU0wl0SiGgz1FdB5YlI',
    appId: '1:36253987314:web:59a46b8d68ea0e3a66bb6b',
    messagingSenderId: '36253987314',
    projectId: 'totemic-client-604',
    authDomain: 'totemic-client-604.firebaseapp.com',
    storageBucket: 'totemic-client-604.appspot.com',
    measurementId: 'G-CDF7WTRH09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKSran7D8iiD-6q_JAAE2LKTb3zioSVeI',
    appId: '1:36253987314:android:47e7f0069d234cf566bb6b',
    messagingSenderId: '36253987314',
    projectId: 'totemic-client-604',
    storageBucket: 'totemic-client-604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnAEeGlseN_7SS1hCPMFlZQ4K2yh0_vRo',
    appId: '1:36253987314:ios:655981b75aa8b0a066bb6b',
    messagingSenderId: '36253987314',
    projectId: 'totemic-client-604',
    storageBucket: 'totemic-client-604.appspot.com',
    iosBundleId: 'com.example.tmpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnAEeGlseN_7SS1hCPMFlZQ4K2yh0_vRo',
    appId: '1:36253987314:ios:655981b75aa8b0a066bb6b',
    messagingSenderId: '36253987314',
    projectId: 'totemic-client-604',
    storageBucket: 'totemic-client-604.appspot.com',
    iosBundleId: 'com.example.tmpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDImEGX1M7dJQAkxU0wl0SiGgz1FdB5YlI',
    appId: '1:36253987314:web:163aaaebf713bfec66bb6b',
    messagingSenderId: '36253987314',
    projectId: 'totemic-client-604',
    authDomain: 'totemic-client-604.firebaseapp.com',
    storageBucket: 'totemic-client-604.appspot.com',
    measurementId: 'G-7KZD576KW8',
  );
}
